# Generated by Django 5.0.2 on 2026-01-05 07:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Custom domain (e.g., support.company.com)', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary domain for this business')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether domain ownership has been verified')),
                ('verification_method', models.CharField(choices=[('dns_txt', 'DNS TXT Record'), ('dns_cname', 'DNS CNAME Record')], default='dns_txt', help_text='Method used to verify domain ownership', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', help_text='Current verification status', max_length=20)),
                ('verification_token', models.CharField(blank=True, help_text='Unique token for domain verification', max_length=64, null=True)),
                ('verification_record_name', models.CharField(blank=True, help_text='DNS record name to create (e.g., _safaridesk-verify)', max_length=255, null=True)),
                ('verification_record_value', models.CharField(blank=True, help_text='DNS record value to set', max_length=255, null=True)),
                ('last_verification_attempt', models.DateTimeField(blank=True, help_text='Last time verification was attempted', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the domain was successfully verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
                'db_table': 'custom_domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivityType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suspicious Activity Type',
                'verbose_name_plural': 'Suspicious Activity Types',
                'db_table': 'suspicious_activity_types',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('first_login', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE'), ('S', 'Suspended'), ('D', 'DEACTIVATED'), ('L', 'LOCKED'), ('B', 'BLOCKED')], default='A', max_length=2)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=100)),
                ('department', models.ManyToManyField(blank=True, to='tenant.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_group', to='auth.group', verbose_name='usergroups')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the business', max_length=255, unique=True)),
                ('organization_size', models.CharField(blank=True, help_text='Number of employee in the business', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the business was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last updated date and time')),
                ('is_active', models.BooleanField(default=True, help_text='Status of the business (active/inactive)')),
                ('website', models.URLField(blank=True, help_text='Website URL of the business', null=True)),
                ('domain', models.CharField(blank=True, help_text='Domain name of the business', max_length=200, null=True)),
                ('domain_url', models.URLField(blank=True, help_text='Domain name of the business', max_length=255, null=True)),
                ('support_url', models.URLField(blank=True, help_text='Support URL of the business', max_length=255, null=True)),
                ('email', models.CharField(blank=True, help_text='Email address of the business', max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, help_text='URL to the business logo', max_length=200, null=True)),
                ('favicon_url', models.CharField(blank=True, help_text='URL to the business favicon', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the business', max_length=200, null=True)),
                ('timezone', models.CharField(blank=True, help_text='Time zone', max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The owner of the business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('first_login', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE'), ('S', 'Suspended'), ('D', 'DEACTIVATED'), ('L', 'LOCKED'), ('B', 'BLOCKED')], default='A', max_length=2)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('allow_login', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('CUSTOMER', 'CUSTOMER'), ('ANONYMOUS', 'ANONYMOUS')], default='CUSTOMER', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.suspiciousactivitytype')),
            ],
            options={
                'verbose_name': 'Suspicious Activity',
                'verbose_name_plural': 'Suspicious Activities',
                'db_table': 'suspicious_activities',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE'), ('S', 'Suspended'), ('D', 'DEACTIVATED'), ('L', 'LOCKED'), ('B', 'BLOCKED')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-id'],
            },
        ),
    ]
