# Generated by Django 5.0.2 on 2026-01-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_slatarget_first_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshoursx',
            name='include_weekends',
            field=models.BooleanField(default=False, help_text='Include weekends (Saturday and Sunday) as working days'),
        ),
        migrations.AlterField(
            model_name='businesshoursx',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='businesshoursx',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='evaluation_method',
            field=models.CharField(choices=[('ticket_creation', 'Ticket creation time'), ('conditions_met', 'Time when conditions are met')], default='ticket_creation', max_length=20),
        ),
        migrations.AlterField(
            model_name='sla',
            name='operational_hours',
            field=models.CharField(choices=[('calendar', 'Calendar Hours (24 hrs x 7 days)'), ('business', 'Business Hours (9 AM - 5 PM, Mon-Fri)'), ('business_with_weekends', 'Business Hours (9 AM - 5 PM, Mon-Sun)'), ('custom', 'Custom Hours')], default='business', max_length=30),
        ),
        migrations.AlterField(
            model_name='slatarget',
            name='operational_hours',
            field=models.CharField(choices=[('calendar', 'Calendar Hours (24 hrs x 7 days)'), ('business', 'Business Hours (9 AM - 5 PM, Mon-Fri)'), ('business_with_weekends', 'Business Hours (9 AM - 5 PM, Mon-Sun)'), ('custom', 'Custom Hours')], default='business', max_length=30),
        ),
        migrations.AlterField(
            model_name='slatarget',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1 - Critical'), ('P2', 'P2 - High'), ('P3', 'P3 - Medium'), ('P4', 'P4 - Low')], max_length=20),
        ),
    ]
